// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Dependency struct {
	BlockerTaskID string `json:"blocker_task_id"`
	BlockedTaskID string `json:"blocked_task_id"`
	CreatedAt     string `json:"created_at"`
}

type Document struct {
	ID        string         `json:"id"`
	FeatureID sql.NullString `json:"feature_id"`
	TaskID    sql.NullString `json:"task_id"`
	Kind      string         `json:"kind"`
	Title     string         `json:"title"`
	Value     string         `json:"value"`
	CreatedAt string         `json:"created_at"`
}

type Feature struct {
	ID          string `json:"id"`
	Slug        string `json:"slug"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Status      string `json:"status"`
	Archived    int64  `json:"archived"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
	PublicID    string `json:"public_id"`
}

type GithubRepositoryAuthCache struct {
	Host            string `json:"host"`
	Owner           string `json:"owner"`
	Repository      string `json:"repository"`
	AuthMethodID    string `json:"auth_method_id"`
	LastSucceededAt string `json:"last_succeeded_at"`
}

type GithubSyncState struct {
	Singleton         int64         `json:"singleton"`
	RunID             string        `json:"run_id"`
	LastAttemptUnix   sql.NullInt64 `json:"last_attempt_unix"`
	LastCompletedUnix sql.NullInt64 `json:"last_completed_unix"`
	Succeeded         int64         `json:"succeeded"`
	Failed            int64         `json:"failed"`
	RunError          string        `json:"run_error"`
}

type IDSequence struct {
	Entity    string `json:"entity"`
	NextValue int64  `json:"next_value"`
}

type ImplementationPlan struct {
	TaskID    string `json:"task_id"`
	Content   string `json:"content"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type PullRequest struct {
	TaskID          string         `json:"task_id"`
	Host            string         `json:"host"`
	Owner           string         `json:"owner"`
	Repository      string         `json:"repository"`
	Number          int64          `json:"number"`
	Url             string         `json:"url"`
	NodeID          string         `json:"node_id"`
	Author          string         `json:"author"`
	AssigneesJson   string         `json:"assignees_json"`
	State           string         `json:"state"`
	Draft           int64          `json:"draft"`
	ReviewState     string         `json:"review_state"`
	Mergeability    string         `json:"mergeability"`
	GithubUpdatedAt sql.NullString `json:"github_updated_at"`
	LastSyncedAt    sql.NullString `json:"last_synced_at"`
	SyncError       string         `json:"sync_error"`
	Stale           int64          `json:"stale"`
}

type Task struct {
	ID        string `json:"id"`
	FeatureID string `json:"feature_id"`
	Title     string `json:"title"`
	Scope     string `json:"scope"`
	Kind      string `json:"kind"`
	Status    string `json:"status"`
	Assignee  string `json:"assignee"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	PublicID  string `json:"public_id"`
}
