// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const addDependency = `-- name: AddDependency :one
INSERT INTO dependencies (blocker_task_id, blocked_task_id, created_at) VALUES (?, ?, ?) RETURNING blocker_task_id, blocked_task_id, created_at
`

type AddDependencyParams struct {
	BlockerTaskID string `json:"blocker_task_id"`
	BlockedTaskID string `json:"blocked_task_id"`
	CreatedAt     string `json:"created_at"`
}

func (q *Queries) AddDependency(ctx context.Context, arg AddDependencyParams) (Dependency, error) {
	row := q.db.QueryRowContext(ctx, addDependency, arg.BlockerTaskID, arg.BlockedTaskID, arg.CreatedAt)
	var i Dependency
	err := row.Scan(&i.BlockerTaskID, &i.BlockedTaskID, &i.CreatedAt)
	return i, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (id, feature_id, task_id, kind, title, value, created_at) VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, feature_id, task_id, kind, title, value, created_at
`

type CreateDocumentParams struct {
	ID        string         `json:"id"`
	FeatureID sql.NullString `json:"feature_id"`
	TaskID    sql.NullString `json:"task_id"`
	Kind      string         `json:"kind"`
	Title     string         `json:"title"`
	Value     string         `json:"value"`
	CreatedAt string         `json:"created_at"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.ID,
		arg.FeatureID,
		arg.TaskID,
		arg.Kind,
		arg.Title,
		arg.Value,
		arg.CreatedAt,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.FeatureID,
		&i.TaskID,
		&i.Kind,
		&i.Title,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const createFeature = `-- name: CreateFeature :one
INSERT INTO features (id, slug, title, description, status, archived, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, slug, title, description, status, archived, created_at, updated_at
`

type CreateFeatureParams struct {
	ID          string `json:"id"`
	Slug        string `json:"slug"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Status      string `json:"status"`
	Archived    int64  `json:"archived"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) CreateFeature(ctx context.Context, arg CreateFeatureParams) (Feature, error) {
	row := q.db.QueryRowContext(ctx, createFeature,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Archived,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, feature_id, title, scope, kind, status, assignee, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, feature_id, title, scope, kind, status, assignee, created_at, updated_at
`

type CreateTaskParams struct {
	ID        string `json:"id"`
	FeatureID string `json:"feature_id"`
	Title     string `json:"title"`
	Scope     string `json:"scope"`
	Kind      string `json:"kind"`
	Status    string `json:"status"`
	Assignee  string `json:"assignee"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ID,
		arg.FeatureID,
		arg.Title,
		arg.Scope,
		arg.Kind,
		arg.Status,
		arg.Assignee,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.FeatureID,
		&i.Title,
		&i.Scope,
		&i.Kind,
		&i.Status,
		&i.Assignee,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDependenciesForFeature = `-- name: DeleteDependenciesForFeature :exec
DELETE FROM dependencies WHERE blocker_task_id IN (SELECT id FROM tasks WHERE feature_id=?)
`

func (q *Queries) DeleteDependenciesForFeature(ctx context.Context, featureID string) error {
	_, err := q.db.ExecContext(ctx, deleteDependenciesForFeature, featureID)
	return err
}

const deleteDependenciesForTask = `-- name: DeleteDependenciesForTask :exec
DELETE FROM dependencies WHERE blocker_task_id=? OR blocked_task_id=?
`

type DeleteDependenciesForTaskParams struct {
	BlockerTaskID string `json:"blocker_task_id"`
	BlockedTaskID string `json:"blocked_task_id"`
}

func (q *Queries) DeleteDependenciesForTask(ctx context.Context, arg DeleteDependenciesForTaskParams) error {
	_, err := q.db.ExecContext(ctx, deleteDependenciesForTask, arg.BlockerTaskID, arg.BlockedTaskID)
	return err
}

const deleteDocument = `-- name: DeleteDocument :execrows
DELETE FROM documents WHERE id=?
`

func (q *Queries) DeleteDocument(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDocument, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteDocumentsForFeature = `-- name: DeleteDocumentsForFeature :exec
DELETE FROM documents WHERE documents.feature_id=?1 OR documents.task_id IN (SELECT tasks.id FROM tasks WHERE tasks.feature_id=?1)
`

func (q *Queries) DeleteDocumentsForFeature(ctx context.Context, featureID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentsForFeature, featureID)
	return err
}

const deleteDocumentsForTask = `-- name: DeleteDocumentsForTask :exec
DELETE FROM documents WHERE task_id=?
`

func (q *Queries) DeleteDocumentsForTask(ctx context.Context, taskID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentsForTask, taskID)
	return err
}

const deleteFeature = `-- name: DeleteFeature :exec
DELETE FROM features WHERE id=?
`

func (q *Queries) DeleteFeature(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFeature, id)
	return err
}

const deletePullRequest = `-- name: DeletePullRequest :execrows
DELETE FROM pull_requests WHERE task_id=?
`

func (q *Queries) DeletePullRequest(ctx context.Context, taskID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePullRequest, taskID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePullRequestsForFeature = `-- name: DeletePullRequestsForFeature :exec
DELETE FROM pull_requests WHERE task_id IN (SELECT id FROM tasks WHERE feature_id=?)
`

func (q *Queries) DeletePullRequestsForFeature(ctx context.Context, featureID string) error {
	_, err := q.db.ExecContext(ctx, deletePullRequestsForFeature, featureID)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id=?
`

func (q *Queries) DeleteTask(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const deleteTasksForFeature = `-- name: DeleteTasksForFeature :exec
DELETE FROM tasks WHERE feature_id=?
`

func (q *Queries) DeleteTasksForFeature(ctx context.Context, featureID string) error {
	_, err := q.db.ExecContext(ctx, deleteTasksForFeature, featureID)
	return err
}

const getFeature = `-- name: GetFeature :one
SELECT id, slug, title, description, status, archived, created_at, updated_at FROM features WHERE id = ?
`

func (q *Queries) GetFeature(ctx context.Context, id string) (Feature, error) {
	row := q.db.QueryRowContext(ctx, getFeature, id)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeatureBySlug = `-- name: GetFeatureBySlug :one
SELECT id, slug, title, description, status, archived, created_at, updated_at FROM features WHERE slug = ?
`

func (q *Queries) GetFeatureBySlug(ctx context.Context, slug string) (Feature, error) {
	row := q.db.QueryRowContext(ctx, getFeatureBySlug, slug)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPullRequestByTask = `-- name: GetPullRequestByTask :one
SELECT task_id, owner, repository, number, url, node_id, author, assignees_json, state, draft, review_state, mergeability, github_updated_at, last_synced_at, sync_error, stale FROM pull_requests WHERE task_id=?
`

func (q *Queries) GetPullRequestByTask(ctx context.Context, taskID string) (PullRequest, error) {
	row := q.db.QueryRowContext(ctx, getPullRequestByTask, taskID)
	var i PullRequest
	err := row.Scan(
		&i.TaskID,
		&i.Owner,
		&i.Repository,
		&i.Number,
		&i.Url,
		&i.NodeID,
		&i.Author,
		&i.AssigneesJson,
		&i.State,
		&i.Draft,
		&i.ReviewState,
		&i.Mergeability,
		&i.GithubUpdatedAt,
		&i.LastSyncedAt,
		&i.SyncError,
		&i.Stale,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, feature_id, title, scope, kind, status, assignee, created_at, updated_at FROM tasks WHERE id=?
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.FeatureID,
		&i.Title,
		&i.Scope,
		&i.Kind,
		&i.Status,
		&i.Assignee,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDependencies = `-- name: ListDependencies :many
SELECT blocker_task_id, blocked_task_id, created_at FROM dependencies ORDER BY created_at, blocker_task_id, blocked_task_id
`

func (q *Queries) ListDependencies(ctx context.Context) ([]Dependency, error) {
	rows, err := q.db.QueryContext(ctx, listDependencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dependency{}
	for rows.Next() {
		var i Dependency
		if err := rows.Scan(&i.BlockerTaskID, &i.BlockedTaskID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDependenciesByFeature = `-- name: ListDependenciesByFeature :many
SELECT d.blocker_task_id, d.blocked_task_id, d.created_at FROM dependencies d JOIN tasks t ON t.id=d.blocker_task_id
WHERE t.feature_id=? ORDER BY d.created_at, d.blocker_task_id, d.blocked_task_id
`

func (q *Queries) ListDependenciesByFeature(ctx context.Context, featureID string) ([]Dependency, error) {
	rows, err := q.db.QueryContext(ctx, listDependenciesByFeature, featureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dependency{}
	for rows.Next() {
		var i Dependency
		if err := rows.Scan(&i.BlockerTaskID, &i.BlockedTaskID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, feature_id, task_id, kind, title, value, created_at FROM documents ORDER BY created_at, id
`

func (q *Queries) ListDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.FeatureID,
			&i.TaskID,
			&i.Kind,
			&i.Title,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatures = `-- name: ListFeatures :many
SELECT id, slug, title, description, status, archived, created_at, updated_at FROM features ORDER BY archived, updated_at DESC, slug
`

func (q *Queries) ListFeatures(ctx context.Context) ([]Feature, error) {
	rows, err := q.db.QueryContext(ctx, listFeatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feature{}
	for rows.Next() {
		var i Feature
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPullRequests = `-- name: ListPullRequests :many
SELECT task_id, owner, repository, number, url, node_id, author, assignees_json, state, draft, review_state, mergeability, github_updated_at, last_synced_at, sync_error, stale FROM pull_requests ORDER BY owner, repository, number
`

func (q *Queries) ListPullRequests(ctx context.Context) ([]PullRequest, error) {
	rows, err := q.db.QueryContext(ctx, listPullRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullRequest{}
	for rows.Next() {
		var i PullRequest
		if err := rows.Scan(
			&i.TaskID,
			&i.Owner,
			&i.Repository,
			&i.Number,
			&i.Url,
			&i.NodeID,
			&i.Author,
			&i.AssigneesJson,
			&i.State,
			&i.Draft,
			&i.ReviewState,
			&i.Mergeability,
			&i.GithubUpdatedAt,
			&i.LastSyncedAt,
			&i.SyncError,
			&i.Stale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, feature_id, title, scope, kind, status, assignee, created_at, updated_at FROM tasks ORDER BY created_at, id
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.FeatureID,
			&i.Title,
			&i.Scope,
			&i.Kind,
			&i.Status,
			&i.Assignee,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByFeature = `-- name: ListTasksByFeature :many
SELECT id, feature_id, title, scope, kind, status, assignee, created_at, updated_at FROM tasks WHERE feature_id=? ORDER BY created_at, id
`

func (q *Queries) ListTasksByFeature(ctx context.Context, featureID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByFeature, featureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.FeatureID,
			&i.Title,
			&i.Scope,
			&i.Kind,
			&i.Status,
			&i.Assignee,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDependency = `-- name: RemoveDependency :execrows
DELETE FROM dependencies WHERE blocker_task_id=? AND blocked_task_id=?
`

type RemoveDependencyParams struct {
	BlockerTaskID string `json:"blocker_task_id"`
	BlockedTaskID string `json:"blocked_task_id"`
}

func (q *Queries) RemoveDependency(ctx context.Context, arg RemoveDependencyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeDependency, arg.BlockerTaskID, arg.BlockedTaskID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateFeature = `-- name: UpdateFeature :one
UPDATE features SET slug=?, title=?, description=?, status=?, archived=?, updated_at=? WHERE id=? RETURNING id, slug, title, description, status, archived, created_at, updated_at
`

type UpdateFeatureParams struct {
	Slug        string `json:"slug"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Status      string `json:"status"`
	Archived    int64  `json:"archived"`
	UpdatedAt   string `json:"updated_at"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateFeature(ctx context.Context, arg UpdateFeatureParams) (Feature, error) {
	row := q.db.QueryRowContext(ctx, updateFeature,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Archived,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks SET title=?, scope=?, status=?, assignee=?, updated_at=? WHERE id=? RETURNING id, feature_id, title, scope, kind, status, assignee, created_at, updated_at
`

type UpdateTaskParams struct {
	Title     string `json:"title"`
	Scope     string `json:"scope"`
	Status    string `json:"status"`
	Assignee  string `json:"assignee"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Title,
		arg.Scope,
		arg.Status,
		arg.Assignee,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.FeatureID,
		&i.Title,
		&i.Scope,
		&i.Kind,
		&i.Status,
		&i.Assignee,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPullRequest = `-- name: UpsertPullRequest :one
INSERT INTO pull_requests (task_id, owner, repository, number, url, node_id, author, assignees_json, state, draft, review_state, mergeability, github_updated_at, last_synced_at, sync_error, stale)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(task_id) DO UPDATE SET owner=excluded.owner, repository=excluded.repository, number=excluded.number,
url=excluded.url, node_id=excluded.node_id, author=excluded.author, assignees_json=excluded.assignees_json,
state=excluded.state, draft=excluded.draft, review_state=excluded.review_state, mergeability=excluded.mergeability,
github_updated_at=excluded.github_updated_at, last_synced_at=excluded.last_synced_at,
sync_error=excluded.sync_error, stale=excluded.stale RETURNING task_id, owner, repository, number, url, node_id, author, assignees_json, state, draft, review_state, mergeability, github_updated_at, last_synced_at, sync_error, stale
`

type UpsertPullRequestParams struct {
	TaskID          string         `json:"task_id"`
	Owner           string         `json:"owner"`
	Repository      string         `json:"repository"`
	Number          int64          `json:"number"`
	Url             string         `json:"url"`
	NodeID          string         `json:"node_id"`
	Author          string         `json:"author"`
	AssigneesJson   string         `json:"assignees_json"`
	State           string         `json:"state"`
	Draft           int64          `json:"draft"`
	ReviewState     string         `json:"review_state"`
	Mergeability    string         `json:"mergeability"`
	GithubUpdatedAt sql.NullString `json:"github_updated_at"`
	LastSyncedAt    sql.NullString `json:"last_synced_at"`
	SyncError       string         `json:"sync_error"`
	Stale           int64          `json:"stale"`
}

func (q *Queries) UpsertPullRequest(ctx context.Context, arg UpsertPullRequestParams) (PullRequest, error) {
	row := q.db.QueryRowContext(ctx, upsertPullRequest,
		arg.TaskID,
		arg.Owner,
		arg.Repository,
		arg.Number,
		arg.Url,
		arg.NodeID,
		arg.Author,
		arg.AssigneesJson,
		arg.State,
		arg.Draft,
		arg.ReviewState,
		arg.Mergeability,
		arg.GithubUpdatedAt,
		arg.LastSyncedAt,
		arg.SyncError,
		arg.Stale,
	)
	var i PullRequest
	err := row.Scan(
		&i.TaskID,
		&i.Owner,
		&i.Repository,
		&i.Number,
		&i.Url,
		&i.NodeID,
		&i.Author,
		&i.AssigneesJson,
		&i.State,
		&i.Draft,
		&i.ReviewState,
		&i.Mergeability,
		&i.GithubUpdatedAt,
		&i.LastSyncedAt,
		&i.SyncError,
		&i.Stale,
	)
	return i, err
}
