// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const acquireGitHubAutoSync = `-- name: AcquireGitHubAutoSync :execrows
UPDATE github_sync_state
SET run_id=?, last_attempt_unix=?, run_error=''
WHERE singleton=1 AND (last_attempt_unix IS NULL OR last_attempt_unix<=?)
`

type AcquireGitHubAutoSyncParams struct {
	RunID             string        `json:"run_id"`
	LastAttemptUnix   sql.NullInt64 `json:"last_attempt_unix"`
	LastAttemptUnix_2 sql.NullInt64 `json:"last_attempt_unix_2"`
}

func (q *Queries) AcquireGitHubAutoSync(ctx context.Context, arg AcquireGitHubAutoSyncParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acquireGitHubAutoSync, arg.RunID, arg.LastAttemptUnix, arg.LastAttemptUnix_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const addDependency = `-- name: AddDependency :one
INSERT INTO dependencies (blocker_task_id, blocked_task_id, created_at) VALUES (?, ?, ?) RETURNING blocker_task_id, blocked_task_id, created_at
`

type AddDependencyParams struct {
	BlockerTaskID string `json:"blocker_task_id"`
	BlockedTaskID string `json:"blocked_task_id"`
	CreatedAt     string `json:"created_at"`
}

func (q *Queries) AddDependency(ctx context.Context, arg AddDependencyParams) (Dependency, error) {
	row := q.db.QueryRowContext(ctx, addDependency, arg.BlockerTaskID, arg.BlockedTaskID, arg.CreatedAt)
	var i Dependency
	err := row.Scan(&i.BlockerTaskID, &i.BlockedTaskID, &i.CreatedAt)
	return i, err
}

const completeGitHubSync = `-- name: CompleteGitHubSync :execrows
UPDATE github_sync_state
SET last_completed_unix=?, succeeded=?, failed=?, run_error=?
WHERE singleton=1 AND run_id=?
`

type CompleteGitHubSyncParams struct {
	LastCompletedUnix sql.NullInt64 `json:"last_completed_unix"`
	Succeeded         int64         `json:"succeeded"`
	Failed            int64         `json:"failed"`
	RunError          string        `json:"run_error"`
	RunID             string        `json:"run_id"`
}

func (q *Queries) CompleteGitHubSync(ctx context.Context, arg CompleteGitHubSyncParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeGitHubSync,
		arg.LastCompletedUnix,
		arg.Succeeded,
		arg.Failed,
		arg.RunError,
		arg.RunID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (id, feature_id, task_id, kind, title, value, created_at) VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, feature_id, task_id, kind, title, value, created_at
`

type CreateDocumentParams struct {
	ID        string         `json:"id"`
	FeatureID sql.NullString `json:"feature_id"`
	TaskID    sql.NullString `json:"task_id"`
	Kind      string         `json:"kind"`
	Title     string         `json:"title"`
	Value     string         `json:"value"`
	CreatedAt string         `json:"created_at"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.ID,
		arg.FeatureID,
		arg.TaskID,
		arg.Kind,
		arg.Title,
		arg.Value,
		arg.CreatedAt,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.FeatureID,
		&i.TaskID,
		&i.Kind,
		&i.Title,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const createFeature = `-- name: CreateFeature :one
INSERT INTO features (id, public_id, slug, title, description, status, archived, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, slug, title, description, status, archived, created_at, updated_at, public_id
`

type CreateFeatureParams struct {
	ID          string `json:"id"`
	PublicID    string `json:"public_id"`
	Slug        string `json:"slug"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Status      string `json:"status"`
	Archived    int64  `json:"archived"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) CreateFeature(ctx context.Context, arg CreateFeatureParams) (Feature, error) {
	row := q.db.QueryRowContext(ctx, createFeature,
		arg.ID,
		arg.PublicID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Archived,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicID,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, public_id, feature_id, title, scope, kind, status, assignee, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, feature_id, title, scope, kind, status, assignee, created_at, updated_at, public_id
`

type CreateTaskParams struct {
	ID        string `json:"id"`
	PublicID  string `json:"public_id"`
	FeatureID string `json:"feature_id"`
	Title     string `json:"title"`
	Scope     string `json:"scope"`
	Kind      string `json:"kind"`
	Status    string `json:"status"`
	Assignee  string `json:"assignee"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ID,
		arg.PublicID,
		arg.FeatureID,
		arg.Title,
		arg.Scope,
		arg.Kind,
		arg.Status,
		arg.Assignee,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.FeatureID,
		&i.Title,
		&i.Scope,
		&i.Kind,
		&i.Status,
		&i.Assignee,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicID,
	)
	return i, err
}

const deleteDependenciesForFeature = `-- name: DeleteDependenciesForFeature :exec
DELETE FROM dependencies WHERE blocker_task_id IN (SELECT id FROM tasks WHERE feature_id=?)
`

func (q *Queries) DeleteDependenciesForFeature(ctx context.Context, featureID string) error {
	_, err := q.db.ExecContext(ctx, deleteDependenciesForFeature, featureID)
	return err
}

const deleteDependenciesForTask = `-- name: DeleteDependenciesForTask :exec
DELETE FROM dependencies WHERE blocker_task_id=? OR blocked_task_id=?
`

type DeleteDependenciesForTaskParams struct {
	BlockerTaskID string `json:"blocker_task_id"`
	BlockedTaskID string `json:"blocked_task_id"`
}

func (q *Queries) DeleteDependenciesForTask(ctx context.Context, arg DeleteDependenciesForTaskParams) error {
	_, err := q.db.ExecContext(ctx, deleteDependenciesForTask, arg.BlockerTaskID, arg.BlockedTaskID)
	return err
}

const deleteDocument = `-- name: DeleteDocument :execrows
DELETE FROM documents WHERE id=?
`

func (q *Queries) DeleteDocument(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDocument, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteDocumentsForFeature = `-- name: DeleteDocumentsForFeature :exec
DELETE FROM documents WHERE documents.feature_id=?1 OR documents.task_id IN (SELECT tasks.id FROM tasks WHERE tasks.feature_id=?1)
`

func (q *Queries) DeleteDocumentsForFeature(ctx context.Context, featureID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentsForFeature, featureID)
	return err
}

const deleteDocumentsForTask = `-- name: DeleteDocumentsForTask :exec
DELETE FROM documents WHERE task_id=?
`

func (q *Queries) DeleteDocumentsForTask(ctx context.Context, taskID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentsForTask, taskID)
	return err
}

const deleteFeature = `-- name: DeleteFeature :exec
DELETE FROM features WHERE id=?
`

func (q *Queries) DeleteFeature(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFeature, id)
	return err
}

const deleteGitHubRepositoryAuthCache = `-- name: DeleteGitHubRepositoryAuthCache :execrows
DELETE FROM github_repository_auth_cache WHERE host=? AND owner=? AND repository=?
`

type DeleteGitHubRepositoryAuthCacheParams struct {
	Host       string `json:"host"`
	Owner      string `json:"owner"`
	Repository string `json:"repository"`
}

func (q *Queries) DeleteGitHubRepositoryAuthCache(ctx context.Context, arg DeleteGitHubRepositoryAuthCacheParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGitHubRepositoryAuthCache, arg.Host, arg.Owner, arg.Repository)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteImplementationPlan = `-- name: DeleteImplementationPlan :execrows
DELETE FROM implementation_plans WHERE task_id=?
`

func (q *Queries) DeleteImplementationPlan(ctx context.Context, taskID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteImplementationPlan, taskID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteImplementationPlansForFeature = `-- name: DeleteImplementationPlansForFeature :exec
DELETE FROM implementation_plans WHERE task_id IN (SELECT id FROM tasks WHERE feature_id=?)
`

func (q *Queries) DeleteImplementationPlansForFeature(ctx context.Context, featureID string) error {
	_, err := q.db.ExecContext(ctx, deleteImplementationPlansForFeature, featureID)
	return err
}

const deleteImplementationPlansForTask = `-- name: DeleteImplementationPlansForTask :exec
DELETE FROM implementation_plans WHERE task_id=?
`

func (q *Queries) DeleteImplementationPlansForTask(ctx context.Context, taskID string) error {
	_, err := q.db.ExecContext(ctx, deleteImplementationPlansForTask, taskID)
	return err
}

const deletePullRequest = `-- name: DeletePullRequest :execrows
DELETE FROM pull_requests WHERE task_id=?
`

func (q *Queries) DeletePullRequest(ctx context.Context, taskID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePullRequest, taskID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePullRequestsForFeature = `-- name: DeletePullRequestsForFeature :exec
DELETE FROM pull_requests WHERE task_id IN (SELECT id FROM tasks WHERE feature_id=?)
`

func (q *Queries) DeletePullRequestsForFeature(ctx context.Context, featureID string) error {
	_, err := q.db.ExecContext(ctx, deletePullRequestsForFeature, featureID)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id=?
`

func (q *Queries) DeleteTask(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const deleteTasksForFeature = `-- name: DeleteTasksForFeature :exec
DELETE FROM tasks WHERE feature_id=?
`

func (q *Queries) DeleteTasksForFeature(ctx context.Context, featureID string) error {
	_, err := q.db.ExecContext(ctx, deleteTasksForFeature, featureID)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, feature_id, task_id, kind, title, value, created_at FROM documents WHERE id=?
`

func (q *Queries) GetDocument(ctx context.Context, id string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.FeatureID,
		&i.TaskID,
		&i.Kind,
		&i.Title,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const getFeature = `-- name: GetFeature :one
SELECT id, slug, title, description, status, archived, created_at, updated_at, public_id FROM features WHERE id = ?
`

func (q *Queries) GetFeature(ctx context.Context, id string) (Feature, error) {
	row := q.db.QueryRowContext(ctx, getFeature, id)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicID,
	)
	return i, err
}

const getFeatureByPublicID = `-- name: GetFeatureByPublicID :one
SELECT id, slug, title, description, status, archived, created_at, updated_at, public_id FROM features WHERE public_id = ?
`

func (q *Queries) GetFeatureByPublicID(ctx context.Context, publicID string) (Feature, error) {
	row := q.db.QueryRowContext(ctx, getFeatureByPublicID, publicID)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicID,
	)
	return i, err
}

const getFeatureBySlug = `-- name: GetFeatureBySlug :one
SELECT id, slug, title, description, status, archived, created_at, updated_at, public_id FROM features WHERE slug = ?
`

func (q *Queries) GetFeatureBySlug(ctx context.Context, slug string) (Feature, error) {
	row := q.db.QueryRowContext(ctx, getFeatureBySlug, slug)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicID,
	)
	return i, err
}

const getGitHubRepositoryAuthCache = `-- name: GetGitHubRepositoryAuthCache :one
SELECT host, owner, repository, auth_method_id, last_succeeded_at FROM github_repository_auth_cache WHERE host=? AND owner=? AND repository=?
`

type GetGitHubRepositoryAuthCacheParams struct {
	Host       string `json:"host"`
	Owner      string `json:"owner"`
	Repository string `json:"repository"`
}

func (q *Queries) GetGitHubRepositoryAuthCache(ctx context.Context, arg GetGitHubRepositoryAuthCacheParams) (GithubRepositoryAuthCache, error) {
	row := q.db.QueryRowContext(ctx, getGitHubRepositoryAuthCache, arg.Host, arg.Owner, arg.Repository)
	var i GithubRepositoryAuthCache
	err := row.Scan(
		&i.Host,
		&i.Owner,
		&i.Repository,
		&i.AuthMethodID,
		&i.LastSucceededAt,
	)
	return i, err
}

const getGitHubSyncState = `-- name: GetGitHubSyncState :one
SELECT singleton, run_id, last_attempt_unix, last_completed_unix, succeeded, failed, run_error FROM github_sync_state WHERE singleton=1
`

func (q *Queries) GetGitHubSyncState(ctx context.Context) (GithubSyncState, error) {
	row := q.db.QueryRowContext(ctx, getGitHubSyncState)
	var i GithubSyncState
	err := row.Scan(
		&i.Singleton,
		&i.RunID,
		&i.LastAttemptUnix,
		&i.LastCompletedUnix,
		&i.Succeeded,
		&i.Failed,
		&i.RunError,
	)
	return i, err
}

const getImplementationPlan = `-- name: GetImplementationPlan :one
SELECT task_id, content, created_at, updated_at FROM implementation_plans WHERE task_id=?
`

func (q *Queries) GetImplementationPlan(ctx context.Context, taskID string) (ImplementationPlan, error) {
	row := q.db.QueryRowContext(ctx, getImplementationPlan, taskID)
	var i ImplementationPlan
	err := row.Scan(
		&i.TaskID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPullRequestByTask = `-- name: GetPullRequestByTask :one
SELECT task_id, host, owner, repository, number, url, node_id, author, assignees_json, state, draft, review_state, mergeability, github_updated_at, last_synced_at, sync_error, stale FROM pull_requests WHERE task_id=?
`

func (q *Queries) GetPullRequestByTask(ctx context.Context, taskID string) (PullRequest, error) {
	row := q.db.QueryRowContext(ctx, getPullRequestByTask, taskID)
	var i PullRequest
	err := row.Scan(
		&i.TaskID,
		&i.Host,
		&i.Owner,
		&i.Repository,
		&i.Number,
		&i.Url,
		&i.NodeID,
		&i.Author,
		&i.AssigneesJson,
		&i.State,
		&i.Draft,
		&i.ReviewState,
		&i.Mergeability,
		&i.GithubUpdatedAt,
		&i.LastSyncedAt,
		&i.SyncError,
		&i.Stale,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, feature_id, title, scope, kind, status, assignee, created_at, updated_at, public_id FROM tasks WHERE id=?
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.FeatureID,
		&i.Title,
		&i.Scope,
		&i.Kind,
		&i.Status,
		&i.Assignee,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicID,
	)
	return i, err
}

const getTaskByPublicID = `-- name: GetTaskByPublicID :one
SELECT id, feature_id, title, scope, kind, status, assignee, created_at, updated_at, public_id FROM tasks WHERE public_id=?
`

func (q *Queries) GetTaskByPublicID(ctx context.Context, publicID string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByPublicID, publicID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.FeatureID,
		&i.Title,
		&i.Scope,
		&i.Kind,
		&i.Status,
		&i.Assignee,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicID,
	)
	return i, err
}

const incrementIDSequence = `-- name: IncrementIDSequence :one
UPDATE id_sequences SET next_value = next_value + 1 WHERE entity = ? RETURNING next_value
`

func (q *Queries) IncrementIDSequence(ctx context.Context, entity string) (int64, error) {
	row := q.db.QueryRowContext(ctx, incrementIDSequence, entity)
	var next_value int64
	err := row.Scan(&next_value)
	return next_value, err
}

const listDependencies = `-- name: ListDependencies :many
SELECT blocker_task_id, blocked_task_id, created_at FROM dependencies ORDER BY created_at, blocker_task_id, blocked_task_id
`

func (q *Queries) ListDependencies(ctx context.Context) ([]Dependency, error) {
	rows, err := q.db.QueryContext(ctx, listDependencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dependency{}
	for rows.Next() {
		var i Dependency
		if err := rows.Scan(&i.BlockerTaskID, &i.BlockedTaskID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDependenciesByFeature = `-- name: ListDependenciesByFeature :many
SELECT d.blocker_task_id, d.blocked_task_id, d.created_at FROM dependencies d JOIN tasks t ON t.id=d.blocker_task_id
WHERE t.feature_id=? ORDER BY d.created_at, d.blocker_task_id, d.blocked_task_id
`

func (q *Queries) ListDependenciesByFeature(ctx context.Context, featureID string) ([]Dependency, error) {
	rows, err := q.db.QueryContext(ctx, listDependenciesByFeature, featureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dependency{}
	for rows.Next() {
		var i Dependency
		if err := rows.Scan(&i.BlockerTaskID, &i.BlockedTaskID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, feature_id, task_id, kind, title, value, created_at FROM documents ORDER BY created_at, id
`

func (q *Queries) ListDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.FeatureID,
			&i.TaskID,
			&i.Kind,
			&i.Title,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatures = `-- name: ListFeatures :many
SELECT id, slug, title, description, status, archived, created_at, updated_at, public_id FROM features ORDER BY archived, updated_at DESC, slug
`

func (q *Queries) ListFeatures(ctx context.Context) ([]Feature, error) {
	rows, err := q.db.QueryContext(ctx, listFeatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feature{}
	for rows.Next() {
		var i Feature
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImplementationPlanTaskIDs = `-- name: ListImplementationPlanTaskIDs :many
SELECT task_id FROM implementation_plans ORDER BY task_id
`

func (q *Queries) ListImplementationPlanTaskIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listImplementationPlanTaskIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var task_id string
		if err := rows.Scan(&task_id); err != nil {
			return nil, err
		}
		items = append(items, task_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPullRequests = `-- name: ListPullRequests :many
SELECT task_id, host, owner, repository, number, url, node_id, author, assignees_json, state, draft, review_state, mergeability, github_updated_at, last_synced_at, sync_error, stale FROM pull_requests ORDER BY host, owner, repository, number
`

func (q *Queries) ListPullRequests(ctx context.Context) ([]PullRequest, error) {
	rows, err := q.db.QueryContext(ctx, listPullRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullRequest{}
	for rows.Next() {
		var i PullRequest
		if err := rows.Scan(
			&i.TaskID,
			&i.Host,
			&i.Owner,
			&i.Repository,
			&i.Number,
			&i.Url,
			&i.NodeID,
			&i.Author,
			&i.AssigneesJson,
			&i.State,
			&i.Draft,
			&i.ReviewState,
			&i.Mergeability,
			&i.GithubUpdatedAt,
			&i.LastSyncedAt,
			&i.SyncError,
			&i.Stale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, feature_id, title, scope, kind, status, assignee, created_at, updated_at, public_id FROM tasks ORDER BY created_at, id
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.FeatureID,
			&i.Title,
			&i.Scope,
			&i.Kind,
			&i.Status,
			&i.Assignee,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByFeature = `-- name: ListTasksByFeature :many
SELECT id, feature_id, title, scope, kind, status, assignee, created_at, updated_at, public_id FROM tasks WHERE feature_id=? ORDER BY created_at, id
`

func (q *Queries) ListTasksByFeature(ctx context.Context, featureID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByFeature, featureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.FeatureID,
			&i.Title,
			&i.Scope,
			&i.Kind,
			&i.Status,
			&i.Assignee,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDependency = `-- name: RemoveDependency :execrows
DELETE FROM dependencies WHERE blocker_task_id=? AND blocked_task_id=?
`

type RemoveDependencyParams struct {
	BlockerTaskID string `json:"blocker_task_id"`
	BlockedTaskID string `json:"blocked_task_id"`
}

func (q *Queries) RemoveDependency(ctx context.Context, arg RemoveDependencyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeDependency, arg.BlockerTaskID, arg.BlockedTaskID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const startGitHubSync = `-- name: StartGitHubSync :exec
UPDATE github_sync_state SET run_id=?, last_attempt_unix=?, run_error='' WHERE singleton=1
`

type StartGitHubSyncParams struct {
	RunID           string        `json:"run_id"`
	LastAttemptUnix sql.NullInt64 `json:"last_attempt_unix"`
}

func (q *Queries) StartGitHubSync(ctx context.Context, arg StartGitHubSyncParams) error {
	_, err := q.db.ExecContext(ctx, startGitHubSync, arg.RunID, arg.LastAttemptUnix)
	return err
}

const updateFeature = `-- name: UpdateFeature :one
UPDATE features SET slug=?, title=?, description=?, status=?, archived=?, updated_at=? WHERE id=? RETURNING id, slug, title, description, status, archived, created_at, updated_at, public_id
`

type UpdateFeatureParams struct {
	Slug        string `json:"slug"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Status      string `json:"status"`
	Archived    int64  `json:"archived"`
	UpdatedAt   string `json:"updated_at"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateFeature(ctx context.Context, arg UpdateFeatureParams) (Feature, error) {
	row := q.db.QueryRowContext(ctx, updateFeature,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Archived,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicID,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks SET title=?, scope=?, status=?, assignee=?, updated_at=? WHERE id=? RETURNING id, feature_id, title, scope, kind, status, assignee, created_at, updated_at, public_id
`

type UpdateTaskParams struct {
	Title     string `json:"title"`
	Scope     string `json:"scope"`
	Status    string `json:"status"`
	Assignee  string `json:"assignee"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Title,
		arg.Scope,
		arg.Status,
		arg.Assignee,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.FeatureID,
		&i.Title,
		&i.Scope,
		&i.Kind,
		&i.Status,
		&i.Assignee,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicID,
	)
	return i, err
}

const upsertGitHubRepositoryAuthCache = `-- name: UpsertGitHubRepositoryAuthCache :exec
INSERT INTO github_repository_auth_cache (host, owner, repository, auth_method_id, last_succeeded_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(host, owner, repository) DO UPDATE SET auth_method_id=excluded.auth_method_id,
last_succeeded_at=excluded.last_succeeded_at
`

type UpsertGitHubRepositoryAuthCacheParams struct {
	Host            string `json:"host"`
	Owner           string `json:"owner"`
	Repository      string `json:"repository"`
	AuthMethodID    string `json:"auth_method_id"`
	LastSucceededAt string `json:"last_succeeded_at"`
}

func (q *Queries) UpsertGitHubRepositoryAuthCache(ctx context.Context, arg UpsertGitHubRepositoryAuthCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertGitHubRepositoryAuthCache,
		arg.Host,
		arg.Owner,
		arg.Repository,
		arg.AuthMethodID,
		arg.LastSucceededAt,
	)
	return err
}

const upsertImplementationPlan = `-- name: UpsertImplementationPlan :one
INSERT INTO implementation_plans (task_id, content, created_at, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(task_id) DO UPDATE SET content=excluded.content, updated_at=excluded.updated_at
RETURNING task_id, content, created_at, updated_at
`

type UpsertImplementationPlanParams struct {
	TaskID    string `json:"task_id"`
	Content   string `json:"content"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) UpsertImplementationPlan(ctx context.Context, arg UpsertImplementationPlanParams) (ImplementationPlan, error) {
	row := q.db.QueryRowContext(ctx, upsertImplementationPlan,
		arg.TaskID,
		arg.Content,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ImplementationPlan
	err := row.Scan(
		&i.TaskID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPullRequest = `-- name: UpsertPullRequest :one
INSERT INTO pull_requests (task_id, host, owner, repository, number, url, node_id, author, assignees_json, state, draft, review_state, mergeability, github_updated_at, last_synced_at, sync_error, stale)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(task_id) DO UPDATE SET host=excluded.host, owner=excluded.owner, repository=excluded.repository, number=excluded.number,
url=excluded.url, node_id=excluded.node_id, author=excluded.author, assignees_json=excluded.assignees_json,
state=excluded.state, draft=excluded.draft, review_state=excluded.review_state, mergeability=excluded.mergeability,
github_updated_at=excluded.github_updated_at, last_synced_at=excluded.last_synced_at,
sync_error=excluded.sync_error, stale=excluded.stale RETURNING task_id, host, owner, repository, number, url, node_id, author, assignees_json, state, draft, review_state, mergeability, github_updated_at, last_synced_at, sync_error, stale
`

type UpsertPullRequestParams struct {
	TaskID          string         `json:"task_id"`
	Host            string         `json:"host"`
	Owner           string         `json:"owner"`
	Repository      string         `json:"repository"`
	Number          int64          `json:"number"`
	Url             string         `json:"url"`
	NodeID          string         `json:"node_id"`
	Author          string         `json:"author"`
	AssigneesJson   string         `json:"assignees_json"`
	State           string         `json:"state"`
	Draft           int64          `json:"draft"`
	ReviewState     string         `json:"review_state"`
	Mergeability    string         `json:"mergeability"`
	GithubUpdatedAt sql.NullString `json:"github_updated_at"`
	LastSyncedAt    sql.NullString `json:"last_synced_at"`
	SyncError       string         `json:"sync_error"`
	Stale           int64          `json:"stale"`
}

func (q *Queries) UpsertPullRequest(ctx context.Context, arg UpsertPullRequestParams) (PullRequest, error) {
	row := q.db.QueryRowContext(ctx, upsertPullRequest,
		arg.TaskID,
		arg.Host,
		arg.Owner,
		arg.Repository,
		arg.Number,
		arg.Url,
		arg.NodeID,
		arg.Author,
		arg.AssigneesJson,
		arg.State,
		arg.Draft,
		arg.ReviewState,
		arg.Mergeability,
		arg.GithubUpdatedAt,
		arg.LastSyncedAt,
		arg.SyncError,
		arg.Stale,
	)
	var i PullRequest
	err := row.Scan(
		&i.TaskID,
		&i.Host,
		&i.Owner,
		&i.Repository,
		&i.Number,
		&i.Url,
		&i.NodeID,
		&i.Author,
		&i.AssigneesJson,
		&i.State,
		&i.Draft,
		&i.ReviewState,
		&i.Mergeability,
		&i.GithubUpdatedAt,
		&i.LastSyncedAt,
		&i.SyncError,
		&i.Stale,
	)
	return i, err
}
